name: Keep Alive

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分鐘執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          max_retries=3
          retry_count=0
          while [ $retry_count -lt $max_retries ]; do
            if curl -sL -w "%{http_code}" "https://translationagent.streamlit.app" -o /dev/null | grep -q "200\|302"; then
              echo "Successfully pinged at $(date)"
              exit 0
            else
              echo "Ping failed, attempt $(($retry_count + 1)) of $max_retries"
              retry_count=$(($retry_count + 1))
              sleep 10
            fi
          done
          echo "All retry attempts failed"
          exit 1 