name: Keep Alive

on:
  schedule:
    - cron: '*/15 * * * *'  # 每15分鐘執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          max_retries=5
          retry_count=0
          success=false
          
          while [ $retry_count -lt $max_retries ]; do
            echo "Attempt $(($retry_count + 1)) of $max_retries at $(date)"
            
            response=$(curl -sL -w "%{http_code}" "https://translationagent.streamlit.app" -o /dev/null || echo "000")
            
            if [[ "$response" =~ ^(200|302)$ ]]; then
              echo "Successfully pinged with status code $response"
              success=true
              break
            else
              echo "Ping failed with status code $response"
              retry_count=$(($retry_count + 1))
              
              if [ $retry_count -lt $max_retries ]; then
                sleep_time=$((30 * $retry_count))  # 逐漸增加等待時間
                echo "Waiting $sleep_time seconds before next attempt..."
                sleep $sleep_time
              fi
            fi
          done
          
          if [ "$success" = true ]; then
            exit 0
          else
            echo "All $max_retries attempts failed"
            exit 1
          fi 