name: Keep Alive

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分鐘執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -sL https://translationagent.streamlit.app > /dev/null
          echo "Pinged at $(date)" 